@url = http://localhost:5001

@restaurant_id = 12ba8ddd-a4f0-47fa-90b5-152eba04c244
@review_id = 9b6ea31f-921c-42d9-b709-8710ff1286ff
@menu_id = 27b93089-c6b6-4cf6-aa45-acfd68e618a0
@image_id = e734b590-dbf6-4f18-8fda-75345c661121

### 식당 생성 (어드민)
POST {{url}}/restaurants
Content-Type: application/json

{
  "name": "테스트 식당",
  "description": "식당 소개",
  "mapUrl": "http://naver.com",
  "address": "서울특별시 중구 ...",
  "phoneNumber": "050-9999-9999",
  "openingHours": "24시간 연중무휴"
}

### 전체 식당 조회
GET {{url}}/restaurants
Content-Type: application/json

### ID를 통해 식당 단건 조회
GET {{url}}/restaurants/{{restaurant_id}}
Content-Type: application/json

### 이름 검색으로 식당 필터링
GET {{url}}/restaurants?search=식당
Content-Type: application/json

### 페이지네이션
GET {{url}}/restaurants?start=0&limit=2
Content-Type: application/json

### 제외 카테고리 설정 (Array를 JSON.stringify 사용해서 쿼리 넣어주세요)
GET {{url}}/restaurants?excludes=["0c77ae98-269f-46d4-ade6-d3a34c5f623e"]
Content-Type: application/json

### 식당 수정 (어드민)
PATCH {{url}}/restaurants/{{restaurant_id}}
Content-Type: application/json

{
  "name": "하하식당",
  "description": "식당소개",
  "mapUrl": "http://naver.com",
  "address": "서울특별시 중구 ...",
  "phoneNumber": "050-9999-9999",
  "openingHours": "24시간 연중무휴"
}

### 식당 제거 (어드민)
DELETE {{url}}/restaurants/{{restaurant_id}}

### 식당에 리뷰 생성
POST {{url}}/restaurants/{{restaurant_id}}/reviews
Content-Type: application/json

{
  "content": "리뷰 내용",
  "score": 5
}

### 식당의 모든 리뷰 조회
GET {{url}}/restaurants/{{restaurant_id}}/reviews

### 식당의 리뷰 수정
PATCH {{url}}/restaurants/{{restaurant_id}}/reviews/{{review_id}}
Content-Type: application/json

{
  "content": "수정된 리뷰 내용",
  "score": 5
}

### 식당의 리뷰 제거
DELETE {{url}}/restaurants/{{restaurant_id}}/reviews/{{review_id}}
Content-Type: application/json


### 식당에 메뉴 생성 (어드민)
POST {{url}}/restaurants/{{restaurant_id}}/menus
Content-Type: application/json

{
  "name": "새로운 메뉴",
  "description": "새로운 메뉴입니다.",
  "price": 50000,
  "imageUrl": "https://picsum.photos/300/300"
}

### 식당의 모든 메뉴 조회
GET {{url}}/restaurants/{{restaurant_id}}/menus

### 식당의 메뉴 수정 (어드민)
PATCH {{url}}/restaurants/{{restaurant_id}}/menus/{{menu_id}}
Content-Type: application/json

{
  "name": "수정된 메뉴",
  "description": "새로운 메뉴입니다.",
  "price": 50000,
  "imageUrl": "https://picsum.photos/300/300"
}

### 식당의 메뉴 삭제 (어드민)
DELETE {{url}}/restaurants/{{restaurant_id}}/menus/{{menu_id}}


### 식당 이미지 생성 (어드민)
POST {{url}}/restaurants/{{restaurant_id}}/images
Content-Type: application/json

{
  "imageUrl": "https://picsum.photos/300/300",
  "caption": "이미지 캡션"
}

### 식당의 모든 이미지 조회
GET {{url}}/restaurants/{{restaurant_id}}/images

### 식당의 이미지 수정 (어드민)
PATCH {{url}}/restaurants/{{restaurant_id}}/images/{{image_id}}
Content-Type: application/json

{
  "imageUrl": "https://picsum.photos/300/300",
  "caption": "수정된 이미지 캡션"
}

### 식당의 이미지 삭제 (어드민)
DELETE {{url}}/restaurants/{{restaurant_id}}/images/{{image_id}}

